[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
nnoremap ,df :Denite file_rec<CR>
nnoremap ,dr :Denite -resume<CR>
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'nelstrom/vim-visual-star-search'

[[plugins]]
repo = 'mattn/emoji-vim'

[[plugins]]
repo = 'AlessandroYorba/Despacio'
hook_add = '''
let g:despacio_Sunset = 1
colorscheme despacio
'''

[[plugins]]
repo = 'tpope/vim-surround'
hook_add = '''
nmap <leader>s cs"'
nmap <leader>d cs'"
nmap <leader>p ysiw)
'''
