[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
nnoremap ,df :Denite file_rec<CR>
nnoremap ,dr :Denite -resume<CR>
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
nnoremap <silent><C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'nelstrom/vim-visual-star-search'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'twitvim/twitvim'

[[plugins]]
repo = 'powerman/vim-plugin-AnsiEsc'

[[plugins]]
repo = 'mattn/vim-oauth'

[[plugins]]
repo = 'mattn/emoji-vim'

[[plugins]]
repo = 'AlessandroYorba/Alduin'

[[plugins]]
repo = 'AlessandroYorba/Despacio'
