[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
nnoremap ,df :Denite file_rec<CR>
nnoremap ,dr :Denite -resume<CR>
'''

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
hook_add = '''
'''

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'nelstrom/vim-visual-star-search'

[[plugins]]
repo = 'mattn/emoji-vim'

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
if (has("termguicolors"))
 set termguicolors
endif
colorscheme tender
'''

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
let g:neoterm_default_mod = 'horizontal'
let g:neoterm_repl_ruby = 'pry'
let g:neoterm_repl_rails = 'rundock rails console --sandbox'
let g:neoterm_automap_keys = ',tt'
tnoremap <silent> <ESC> <C-\><C-n>
nnoremap <silent> @r :TREPLSendLine<CR>
vnoremap <silent> @r :TREPLSendSelection<CR>
nnoremap <silent> @c :T ./bin/rails console<CR>
nnoremap <silent> @s :T ./bin/rails console --sandbox<CR>
nnoremap <silent> @dc :T rundock rails console<CR>
nnoremap <silent> @ds :T rundock rails console --sandbox<CR>
nnoremap <silent> @p :T pry<CR>
nnoremap <silent> ,th :call neoterm#close()<CR>
nnoremap <silent> ,th :call neoterm#close()<CR>
'''

[[plugins]]
repo = 'tpope/vim-surround'
hook_add = '''
nmap <Space>s cs"'
nmap <Space>d cs'"
nmap <Space>p ysiw)
'''

[[plugins]]
repo = 'mattn/sonictemplate-vim'
hook_add = '''
let g:sonictemplate_vim_template_dir = $XDG_CONFIG_HOME . '/nvim/template'
'''

[[plugins]]
repo = 'yuttie/comfortable-motion.vim'
hook_add = '''
let g:comfortable_motion_scroll_down_key = "j"
let g:comfortable_motion_scroll_up_key = "k"
'''
