[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  "set background=dark
  au MyAutoCmd VimEnter * nested colorscheme molokai
'''

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'nelstrom/vim-visual-star-search'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'tpope/vim-surround'
