[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
nnoremap ,df :Denite file_rec<CR>
nnoremap ,dr :Denite -resume<CR>
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'nelstrom/vim-visual-star-search'

[[plugins]]
repo = 'mattn/emoji-vim'

[[plugins]]
repo = 'AlessandroYorba/Despacio'
hook_add = '''
let g:despacio_Sunset = 1
colorscheme despacio
'''

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
let g:neoterm_position = 'horizontal'
let g:neoterm_repl_ruby = 'pry'
let g:neoterm_repl_rails = 'docker-compose run web rails console --sandbox'
let g:neoterm_automap_keys = ',tt'
tnoremap <silent> <ESC> <C-\><C-n>
nnoremap <silent> @r :TREPLSendLine<CR>
vnoremap <silent> @r :TREPLSendSelection<CR>
nnoremap <silent> @c :T ./bin/rails console<CR>
nnoremap <silent> @s :T ./bin/rails console --sandbox<CR>
nnoremap <silent> @dc :T docker-compose run web rails console<CR>
nnoremap <silent> @ds :T docker-compose run web rails console --sandbox<CR>
nnoremap <silent> @p :T pry<CR>
nnoremap <silent> ,th :call neoterm#close()<CR>
nnoremap <silent> ,th :call neoterm#close()<CR>
'''

[[plugins]]
repo = 'tpope/vim-surround'
hook_add = '''
nmap <leader>s cs"'
nmap <leader>d cs'"
nmap <leader>p ysiw)
'''
