[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'derekwyatt/vim-scala'

[[plugins]]
repo = 'itchyny/vim-haskell-indent'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'

[[plugins]]
repo = 'ujihisa/neco-ghc'

[[plugins]]
repo = 'ujihisa/ref-hoogle'

"repo = 'kassio/neoterm'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
            \ 'split' : '',
			\ 'runner' : 'vimproc',
			\ 'runner/vimproc/updatetime' : 10,
                        \ 'markdown' : {
                        \ 'outputter' : 'browser',
                        \ },
			\ 'tex' : {
			\ 'command' : 'latd',
			\ 'cmdopt' : '',
			\ 'exec' : ['%c %o %s'] 
			\ },
                        \ 'haskell' : {
                        \ 'command' : 'stack',
                        \ 'cmdopt' : 'runhaskell',
                        \ 'exec' : ['%c %o %s']
                        \ },
			\}
'''

