[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'derekwyatt/vim-scala'

[[plugins]]
repo = 'itchyny/vim-haskell-indent'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'

[[plugins]]
repo = 'ujihisa/neco-ghc'

[[plugins]]
repo = 'ujihisa/ref-hoogle'

[[plugins]]
repo = 'kassio/neoterm'
