[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
nnoremap <silent> <C-e> :Defx -resume -split=floating -floating-preview<CR>
'''
hook_source = '''
autocmd FileType defx call s:defx_my_settings()
function! s:defx_my_settings() abort
  " Define mappings
  nnoremap <silent><buffer><expr> <CR>
  \ defx#do_action('multi', ['drop', 'quit'])
  nnoremap <silent><buffer><expr> p
  \ defx#do_action('preview')
  nnoremap <silent><buffer><expr> o
  \ defx#do_action('open_tree', ['toggle', 'nested'])
  nnoremap <silent><buffer><expr> K
  \ defx#do_action('new_directory')
  nnoremap <silent><buffer><expr> N
  \ defx#do_action('new_file')
  nnoremap <silent><buffer><expr> d
  \ defx#do_action('remove')
  nnoremap <silent><buffer><expr> r
  \ defx#do_action('rename')
  nnoremap <silent><buffer><expr> !
  \ defx#do_action('execute_system')
  nnoremap <silent><buffer><expr> .
  \ defx#do_action('toggle_ignored_files')
  nnoremap <silent><buffer><expr> u
  \ defx#do_action('cd', ['..'])
  nnoremap <silent><buffer><expr> q
  \ defx#do_action('quit')
  nnoremap <silent><buffer><expr> j
  \ line('.') == line('$') ? 'gg' : 'j'
  nnoremap <silent><buffer><expr> k
  \ line('.') == 1 ? 'G' : 'k'
  nnoremap <silent><buffer><expr> <C-r>
  \ defx#do_action('redraw')
endfunction
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
let g:rustfmt_autosave = 1
'''
on_ft = ['rust']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescriptreact']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['typescriptreact']

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
nnoremap <Leader>r :QuickRun<cr>
'''
hook_source = '''
let g:quickrun_config = {
\   "rust": {
\     "exec": "cargo run",
\   },
\   "typescript": {
\     "exec": "deno run -A %s",
\   },
\ }
'''
